
services:
  order-service:
    build: ./orderService
  infra-service:
    build: ./infrastructureService
    environment:
      - SPRING_MAIL_USERNAME=${MAIL_USER}
      - SPRING_MAIL_PASSWORD=${MAIL_PASS}
  payment-service:
    build: ./paymentService
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq-broker

  # Baza danych dla Order Service
  order-db:
    image: postgres:15
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  # Serwer FTP dla Infra Service (do faktur)
  ftp-server:
    image: delfer/alpine-ftp-server
    environment:
      - USERS=user|pass
    ports:
      - "21:21"
      - "21000-21010:21000-21010"

